#define BB_ABYSS_TENTACLE_MODE "BB_abyss_tentacle_mode"
#define BB_ABYSS_TENTACLE_GRABBED "BB_abyss_tentacle_grabbed"

#define BB_NPC_CURRENT_FLEE_TARGET "BB_npc_current_flee_target"
#define BB_NPC_STALE_BEACONS "BB_npc_stale_beacons"

#define BB_NPC_ATTRIBUTE_AGGRESSION "BB_npc_attribute_aggression"
#define BB_NPC_ATTRIBUTE_CONFIDENCE "BB_npc_attribute_confidence"
#define BB_NPC_ATTRIBUTE_ENERGY "BB_npc_attribute_energy"
#define BB_NPC_ATTRIBUTE_RESPONSIBILITY "BB_npc_attribute_responsibility"
